### ISSUE TITLE
Axios Setting

### ISSUE THREAD

**Issue by rhehfl** [modern-agile-team/8term-coko-Front#30]
## 📌 이슈 내용
악시오스 라이브러리를 사용해서 기본 인스턴스 세팅과 인터셉터 설정 하겠습니다
### 구현 내용
- [x] 세부 작업 1 백엔드 url을 포함한 axios config 인스턴스 생성
- [x] 세부 작업 2axios config 인스턴스의 request, response 인터셉터 생성
- [ ] 세부 작업 3 각 인터셉터에 대한 로직 구현

**Comment by rhehfl** [comment]
인스턴스와 인터셉터는 생성하였습니다 이름은 axiosConfig으로 했는데 개인적으로는 인스턴스 이름 server로 하는건 어떨까 생각중입니다.
디테일한 로직은 백엔드 cors 문제  해결 후 실제 요청을 보내보면서 확인 해보겠습니다

**Comment by bluetree7878** [comment]
좋습니다. 인스턴스 이름 server도 괜찮은 것 같고, api라고 짓는 것도 괜찮을 것 같아요
